line-length = 100
indent-width = 4
fix = true
unsafe-fixes = false
cache-dir = "~/.cache/ruff"

[format]
# quote-style = "single"
line-ending = "auto"
indent-style = "space"
docstring-code-format = true
# docstring-code-line-length = 20

[lint]
select = ["ALL"]
ignore = [
  "RUF001",
  "RUF002",
  "B008",
  "Q000",
  "D100",
  "D101",
  "FA102",
  "RUF012",
  "RUF006",
  "D102",
  "D107",
  "INP001",
  "PGH003",
  "ANN",
  "D103",
  "TRY003",
  "EM101",
  "D104",
  "D205",
  "D212",
  "RSE102",
  "S101",
  "RET505",
  "D105",
  "UP008",
  "D106",
  "ERA001",
  "FBT001",
  "FBT002",
  "SIM117",
  "G004",
  "TRY400",
  "PERF203",
]

[lint.flake8-annotations]
mypy-init-return = true
